version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: images
      POSTGRES_USER: santiago
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432 
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=santiago8628@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80